document.addEventListener("DOMContentLoaded", () => {
  const form = document.getElementById("customer-form");
  const merchDetails = document.getElementById("merch-details");
  const clothingItemsInput = document.getElementById("clothing-items");

  // Show/Hide Merch Details Based on Selection
  form.addEventListener("change", () => {
    const services = Array.from(form.querySelectorAll("input[name='services']:checked")).map(
      (input) => input.value
    );
    merchDetails.style.display = services.includes("merchstore") ? "block" : "none";
  });

  // Handle Form Submission
  form.addEventListener("submit", (e) => {
    e.preventDefault();

    // Collect Form Data
    const formData = new FormData(form);
    const companyName = formData.get("company_name");
    const industry = formData.get("industry");
    const brandColors = formData.get("brand_colors") || "Not provided";
    const futureGoals = formData.get("future_goals") || "Not shared";
    const additionalInfo = formData.get("additional_info") || "None";
    const selectedServices = formData.getAll("services");
    const numRequirements = parseInt(formData.get("requirements") || 0);
    const clothingItems = parseInt(clothingItemsInput.value || 0);

    // Calculate Pricing
    const serviceFee = selectedServices.length * 750; // Premium pricing per service
    const requirementsFee = numRequirements * 100;
    const merchFee = selectedServices.includes("merchstore") ? clothingItems * 120 + clothingItems * 12 : 0;
    const totalEstimate = serviceFee + requirementsFee + merchFee;

    // Generate a Detailed Proposal
    const servicesList = selectedServices
      .map((service) => `- ${service.replace(/_/g, " ").toUpperCase()}`)
      .join("\n");

    const proposalContent = `
${companyName}: Tailored Proposal from Brand On
==================================================

Hello ${companyName},

Thank you for choosing Brand On to elevate your business! Based on the details provided, we’ve crafted a proposal tailored to your industry (${industry}) and your goals for growth and visibility.

### Highlights of Your Proposal:

1. **Your Business at a Glance:**
   - Industry: ${industry}
   - Brand Colors: ${brandColors}
   - Future Goals: ${futureGoals}

2. **Selected Services:**
   ${servicesList || "No services selected yet"}

3. **Our Recommendations:**
   We’re excited to partner with you to achieve your goals. Our services are designed to solve key challenges in your industry, ensuring you maximize brand recognition, streamline operations, and scale profitably.

   ${selectedServices.includes("merchstore") ? `#### Merchandise Solution:
   - Empower your brand with a no-inventory, print-on-demand merchandise store.
   - Each order incurs a 10% hosting fee, allowing us to offset operational costs and ensure your store runs smoothly year-round. This model is designed to save you money while delivering top-tier quality!` : ""}

4. **Pricing Breakdown:**
   - Professional Service Fee (based on selected services): $${serviceFee.toFixed(2)}
   - Complexity/Requirements Fee: $${requirementsFee.toFixed(2)}
   ${merchFee > 0 ? `- Merchandising Setup Fee: $${merchFee.toFixed(2)}` : ""}
   - **Total Estimate**: $${totalEstimate.toFixed(2)}

### Why Brand On?
We don’t just deliver services; we build **partnerships** that empower our clients to thrive. From modern branding to seamless web design and innovative merchandise solutions, we specialize in creating tailored strategies that drive results.

Our clients have achieved:
- **300% Sales Growth** through better web design.
- **Unmatched Brand Loyalty** with personalized merch stores.
- **Increased ROI** on social media campaigns.

Your vision is our mission, and we’re excited to help you reach new heights.

---

### Next Steps:
1. Review this proposal and identify any refinements you’d like.
2. Reach out to us directly at **info@brandonmarketing.ca** to get started.
3. Let’s schedule a call to finalize details and launch your solutions.

Thank you for trusting us with your brand’s success. We can’t wait to work together!

Sincerely,  
**The Brand On Team**  
"Switch On Your Success."

==================================================
Generated by Brand On’s Proposal System
    `;

    // Generate PDF
    const { jsPDF } = window.jspdf;
    const pdf = new jsPDF();

    pdf.setFont("Helvetica", "normal");
    pdf.text(proposalContent, 10, 10, { maxWidth: 190 });

    // Save the PDF
    pdf.save(`${companyName}_Proposal.pdf`);
  });
});
